/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      fontSize: {
        display: ['var(--font-size-display)', { lineHeight: 'var(--line-height-display)', fontWeight: 'var(--font-weight-black)' }],
        title: ['var(--font-size-title)', { lineHeight: 'var(--line-height-title)', fontWeight: 'var(--font-weight-bold)' }],
        subtitle: ['var(--font-size-subtitle)', { lineHeight: 'var(--line-height-subtitle)', fontWeight: 'var(--font-weight-semibold)' }],
        text: ['var(--font-size-body)', { lineHeight: 'var(--line-height-body)', fontWeight: 'var(--font-weight-regular)' }],
        highlight: ['var(--font-size-body)', { lineHeight: 'var(--line-height-body)', fontWeight: 'var(--font-weight-semibold)' }],
        label: ['var(--font-size-label)', { lineHeight: 'var(--line-height-label)', fontWeight: 'var(--font-weight-bold)', textTransform: 'uppercase' }],
        caption: ['var(--font-size-caption)', { lineHeight: 'var(--line-height-caption)', fontWeight: 'var(--font-weight-regular)' }],
      },
      colors: {
        surface: {
          app: 'var(--color-offwhite)',
          raised: 'var(--color-cream)',
          muted: 'var(--color-cream)',
          subtle: 'var(--color-beige)',
          strong: 'var(--color-sand)',
        },
        text: {
          main: 'var(--color-text-main)',
          muted: 'var(--color-text-muted)',
          inverse: 'var(--color-white-pure)',
        },
        border: {
          soft: 'var(--color-border-soft)',
          strong: 'var(--color-border-strong)',
        },
        accent: {
          main: 'var(--color-accent-main)',
          light: 'var(--color-accent-light)',
          soft: 'var(--color-accent-soft)',
          dark: 'var(--color-accent-dark)',
        },
        tomato: {
          main: 'var(--color-tomato-main)',
          light: 'var(--color-tomato-light)',
          soft: 'var(--color-tomato-soft)',
          dark: 'var(--color-tomato-dark)',
        },
        success: {
          main: 'var(--color-success-main)',
          soft: 'var(--color-success-soft)',
          dark: 'var(--color-success-dark)',
        },
        info: {
          main: 'var(--color-info-main)',
          soft: 'var(--color-info-soft)',
          dark: 'var(--color-info-dark)',
        },
        warning: {
          main: 'var(--color-warning-main)',
          soft: 'var(--color-warning-soft)',
          dark: 'var(--color-warning-dark)',
        },
        component: {
          button: {
            primary: {
              bg: 'var(--component-button-primary-bg)',
              pressed: 'var(--component-button-primary-bg-pressed)',
              text: 'var(--component-button-primary-text)',
            },
            danger: {
              bg: 'var(--component-button-danger-bg)',
              pressed: 'var(--component-button-danger-bg-pressed)',
            },
          },
          input: {
            bg: 'var(--component-input-bg)',
            border: 'var(--component-input-border)',
            focus: 'var(--component-input-border-focus)',
          },
          card: {
            bg: 'var(--component-card-bg)',
            border: 'var(--component-card-border)',
          },
        },
        primary: {
          main: 'var(--color-primary-main)',
          light: 'var(--color-primary-light)',
          soft: 'var(--color-primary-soft)',
          dark: 'var(--color-primary-dark)',
        },
        secondary: {
          main: 'var(--color-secondary-main)',
          light: 'var(--color-secondary-light)',
          soft: 'var(--color-secondary-soft)',
          dark: 'var(--color-secondary-dark)',
        },
        white: {
          pure: 'var(--color-white-pure)',
          base: 'var(--color-white-base)',
          soft: 'var(--color-white-soft)',
        },
        black: {
          main: 'var(--color-black-main)',
          soft: 'var(--color-black-soft)',
          light: 'var(--color-black-light)',
        },
        gray: {
          300: 'var(--color-gray-300)',
          400: 'var(--color-gray-400)',
          500: 'var(--color-gray-500)',
          700: 'var(--color-gray-700)',
        }
      },
      fontFamily: {
        sans: ["Helvetica", "Arial", "sans-serif"],
      },
      fontWeight: {
        regular: "var(--font-weight-regular)",
        semibold: "var(--font-weight-semibold)",
        bold: "var(--font-weight-bold)",
        black: "var(--font-weight-black)",
      },
      lineHeight: {
        display: "var(--line-height-display)",
        title: "var(--line-height-title)",
        subtitle: "var(--line-height-subtitle)",
        body: "var(--line-height-body)",
        label: "var(--line-height-label)",
        caption: "var(--line-height-caption)",
      },
      letterSpacing: {
        tight: "var(--letter-spacing-tight)",
        normal: "var(--letter-spacing-normal)",
        wide: "var(--letter-spacing-wide)",
        label: "var(--letter-spacing-label)",
      },
      borderRadius: {
        none: "var(--radius-none)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
      },
      borderWidth: {
        DEFAULT: "var(--border-width-thin)",
        0: "0px",
        hairline: "var(--border-width-hairline)",
        thin: "var(--border-width-thin)",
      },
      boxShadow: {
        sm: "var(--shadow-none)",
        DEFAULT: "var(--shadow-none)",
        md: "var(--shadow-none)",
        lg: "var(--shadow-none)",
        xl: "var(--shadow-none)",
        "2xl": "var(--shadow-none)",
      },
      spacing: {
        base: "var(--space-base)",
        "1": "var(--space-micro)",
        "2": "var(--space-compact)",
        "3": "var(--space-title-content)",
        "4": "var(--space-screen)",
        "5": "var(--space-card)",
        "6": "var(--space-related)",
        "8": "var(--space-category)",
        "10": "var(--space-page)",
        "12": "var(--space-empty-state)",
        micro: "var(--space-micro)",
        compact: "var(--space-compact)",
        "title-content": "var(--space-title-content)",
        screen: "var(--space-screen)",
        card: "var(--space-card)",
        related: "var(--space-related)",
        category: "var(--space-category)",
        page: "var(--space-page)",
        "empty-state": "var(--space-empty-state)",
        "screen-x": "var(--layout-screen-padding-x)",
        "screen-y": "var(--layout-screen-padding-y)",
        "screen-y-comfortable": "var(--layout-screen-padding-y-comfortable)",
        "grid-gutter": "var(--layout-grid-gutter)",
        "content-gap": "var(--layout-content-gap)",
        "section-gap": "var(--layout-section-gap)",
        "page-gap": "var(--layout-page-gap)",
      },
      width: {
        "icon-sm": "var(--size-icon-sm)",
        "icon-md": "var(--size-icon-md)",
        "icon-lg": "var(--size-icon-lg)",
        "avatar-sm": "var(--size-avatar-sm)",
        "avatar-md": "var(--size-avatar-md)",
        "avatar-lg": "var(--size-avatar-lg)",
        "sheet-handle": "var(--size-bottom-sheet-handle-width)",
      },
      height: {
        "icon-sm": "var(--size-icon-sm)",
        "icon-md": "var(--size-icon-md)",
        "icon-lg": "var(--size-icon-lg)",
        "touch-target": "var(--size-touch-target)",
        "control-sm": "var(--size-control-sm)",
        "control-md": "var(--size-control-md)",
        "control-lg": "var(--size-control-lg)",
        "input-md": "var(--size-input-md)",
        "avatar-sm": "var(--size-avatar-sm)",
        "avatar-md": "var(--size-avatar-md)",
        "avatar-lg": "var(--size-avatar-lg)",
        "tabbar": "var(--size-tabbar-height)",
        "sheet-handle": "var(--size-bottom-sheet-handle-height)",
      },
      minHeight: {
        "touch-target": "var(--size-touch-target)",
        "control-sm": "var(--size-control-sm)",
        "control-md": "var(--size-control-md)",
        "control-lg": "var(--size-control-lg)",
        "input-md": "var(--size-input-md)",
      },
      transitionDuration: {
        fast: "var(--motion-duration-fast)",
        base: "var(--motion-duration-base)",
        slow: "var(--motion-duration-slow)",
      },
      transitionTimingFunction: {
        standard: "var(--motion-easing-standard)",
        emphasized: "var(--motion-easing-emphasized)",
      },
    },
  },
  plugins: [],
}
