/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      fontSize: {
        display: ['var(--font-size-display)', { lineHeight: 'var(--line-height-display)', fontWeight: '900' }],
        title: ['var(--font-size-title)', { lineHeight: 'var(--line-height-title)', fontWeight: '700' }],
        subtitle: ['var(--font-size-subtitle)', { lineHeight: 'var(--line-height-subtitle)', fontWeight: '600' }],
        text: ['var(--font-size-body)', { lineHeight: 'var(--line-height-body)', fontWeight: '400' }],
        highlight: ['var(--font-size-body)', { lineHeight: 'var(--line-height-body)', fontWeight: '600' }],
        label: ['var(--font-size-label)', { lineHeight: 'var(--line-height-label)', fontWeight: '700', textTransform: 'uppercase' }],
        caption: ['var(--font-size-caption)', { lineHeight: 'var(--line-height-caption)', fontWeight: '400' }],
      },
      colors: {
        background: 'var(--color-background)',
        surface: {
          DEFAULT: 'var(--color-surface)',
          elevated: 'var(--color-surface-elevated)',
          disabled: 'var(--color-surface-disabled)',
        },
        border: {
          subtle: 'var(--color-border-subtle)',
          strong: 'var(--color-border-strong)',
          control: 'var(--color-border-control)',
          'control-hover': 'var(--color-border-control-hover)',
          focus: 'var(--color-border-focus)',
        },
        text: {
          primary: 'var(--color-text-primary)',
          secondary: {
            surface: 'var(--color-text-secondary-surface)',
            background: 'var(--color-text-secondary-background)',
            DEFAULT: 'var(--color-text-secondary-surface)',
          },
          disabled: 'var(--color-text-disabled)',
          inverse: 'var(--color-text-inverse)',
        },
        primary: {
          DEFAULT: 'var(--color-primary)',
        },
        protein: 'var(--color-protein)',
        carbohydrate: 'var(--color-carbohydrate)',
        fat: 'var(--color-fat)',
        info: {
          DEFAULT: 'var(--color-info)',
        },
        warning: {
          DEFAULT: 'var(--color-warning)',
        },
        success: {
          DEFAULT: 'var(--color-success)',
        },
        error: 'var(--color-error)',
        link: {
          DEFAULT: 'var(--color-link)',
          visited: 'var(--color-link-visited)',
        },
        data: {
          1: 'var(--color-data-1)',
          2: 'var(--color-data-2)',
          3: 'var(--color-data-3)',
          4: 'var(--color-data-4)',
          5: 'var(--color-data-5)',
          6: 'var(--color-data-6)',
        },
      },
      fontFamily: {
        sans: ["Helvetica", "Arial", "sans-serif"],
      },
      fontWeight: {
        regular: "400",
        semibold: "600",
        bold: "700",
        black: "900",
      },
      lineHeight: {
        display: "var(--line-height-display)",
        title: "var(--line-height-title)",
        subtitle: "var(--line-height-subtitle)",
        body: "var(--line-height-body)",
        label: "var(--line-height-label)",
        caption: "var(--line-height-caption)",
      },
      letterSpacing: {
        tight: "var(--letter-spacing-tight)",
        normal: "var(--letter-spacing-normal)",
        wide: "var(--letter-spacing-wide)",
        label: "var(--letter-spacing-label)",
      },
      borderRadius: {
        none: "var(--radius-none)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
      },
      borderWidth: {
        DEFAULT: "var(--border-width-thin)",
        0: "0px",
        hairline: "var(--border-width-hairline)",
        thin: "var(--border-width-thin)",
      },
      boxShadow: {
        sm: "var(--shadow-none)",
        DEFAULT: "var(--shadow-none)",
        md: "var(--shadow-none)",
        lg: "var(--shadow-none)",
        xl: "var(--shadow-none)",
        "2xl": "var(--shadow-none)",
        floating: "var(--shadow-floating)",
      },
      spacing: {
        base: "var(--space-base)",
        "1": "var(--space-micro)",
        "2": "var(--space-compact)",
        "3": "var(--space-title-content)",
        "4": "var(--space-screen)",
        "5": "var(--space-card)",
        "6": "var(--space-related)",
        "8": "var(--space-category)",
        "10": "var(--space-page)",
        "12": "var(--space-empty-state)",
        micro: "var(--space-micro)",
        compact: "var(--space-compact)",
        "title-content": "var(--space-title-content)",
        screen: "var(--space-screen)",
        card: "var(--space-card)",
        related: "var(--space-related)",
        category: "var(--space-category)",
        page: "var(--space-page)",
        "empty-state": "var(--space-empty-state)",
        "screen-x": "var(--layout-screen-padding-x)",
        "screen-y": "var(--layout-screen-padding-y)",
        "screen-y-comfortable": "var(--layout-screen-padding-y-comfortable)",
        "grid-gutter": "var(--layout-grid-gutter)",
        "content-gap": "var(--layout-content-gap)",
        "section-gap": "var(--layout-section-gap)",
        "page-gap": "var(--layout-page-gap)",
        "content-bottom": "var(--layout-content-bottom-space)",
        "overlay-action": "var(--layout-overlay-action-space)",
        "form-bottom": "var(--layout-form-bottom-space)",
        "long-form-bottom": "var(--layout-long-form-bottom-space)",
      },
      width: {
        "icon-sm": "var(--size-icon-sm)",
        "icon-md": "var(--size-icon-md)",
        "icon-lg": "var(--size-icon-lg)",
        "avatar-sm": "var(--size-avatar-sm)",
        "avatar-md": "var(--size-avatar-md)",
        "avatar-lg": "var(--size-avatar-lg)",
        "sheet-handle": "var(--size-bottom-sheet-handle-width)",
      },
      height: {
        "icon-sm": "var(--size-icon-sm)",
        "icon-md": "var(--size-icon-md)",
        "icon-lg": "var(--size-icon-lg)",
        "touch-target": "var(--size-touch-target)",
        "control-sm": "var(--size-control-sm)",
        "control-md": "var(--size-control-md)",
        "control-lg": "var(--size-control-lg)",
        "input-md": "var(--size-input-md)",
        "avatar-sm": "var(--size-avatar-sm)",
        "avatar-md": "var(--size-avatar-md)",
        "avatar-lg": "var(--size-avatar-lg)",
        "tabbar": "var(--size-tabbar-height)",
        "sheet-handle": "var(--size-bottom-sheet-handle-height)",
        "selection-sheet": "var(--size-selection-sheet-height)",
        "color-swatch": "var(--size-color-swatch-height)",
        "food-card": "var(--size-food-card)",
      },
      minHeight: {
        "touch-target": "var(--size-touch-target)",
        "control-sm": "var(--size-control-sm)",
        "control-md": "var(--size-control-md)",
        "control-lg": "var(--size-control-lg)",
        "input-md": "var(--size-input-md)",
      },
      maxHeight: {
        sheet: "var(--size-bottom-sheet-max-height)",
      },
      flex: {
        2: "2 2 0%",
      },
      transitionDuration: {
        fast: "var(--motion-duration-fast)",
        base: "var(--motion-duration-base)",
        slow: "var(--motion-duration-slow)",
      },
      transitionTimingFunction: {
        standard: "var(--motion-easing-standard)",
        emphasized: "var(--motion-easing-emphasized)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down var(--motion-duration-base) var(--motion-easing-standard)",
        "accordion-up": "accordion-up var(--motion-duration-base) var(--motion-easing-standard)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
